version: '3.8'
services:
  spring-boot:
    image: backend:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      service-db:
        condition: service_healthy
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/postgres

  service-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres", "--quiet" ]
        interval: 1s
        timeout: 5s
        retries: 10

volumes:
  db-data: