version: '3.8'
services:

  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8080"
    depends_on:
      service-db:
        condition: service_healthy
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres

  service-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "15432:5432"
    restart: unless-stopped


volumes:
  db-data:
  pgadmin-data:



